[package]
name = "bitcoin-rpc"
version = "0.1.0"
edition = "2021"
description = "Bitcoin RPC"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
license = "MIT"
homepage = "https://github.com/p2kishimoto/bitcoin-rpc"
repository = "https://github.com/p2kishimoto/bitcoin-rpc"
keywords = ["bitcoin", "bitcoin-rpc", "json-rpc"]
readme = "README.md"

[dependencies]
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
